# Default values for helm-fluentd-kinesis-firehose.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: fluent/fluentd-kubernetes-daemonset
  tag: v0.12-debian-kinesis
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

fluentEnvs:
  assumeRole: false
  roleARN: ""
  roleSession: ""
  kinesisRegion: "eu-west-1"
  kinesisStreamName: "cxcloud"
  kinesisIncludeTimeKey: "true"
  bufferChunkLimitSize: "2M"
  bufferQueueLimitLength: "32"
  instanceProfileCredentials: false
  instanceProfileIPAddress: "169.254.169.254"
  instanceProfilePort: "80"

# The configuration files can be overrided by adding the variables,
# fluentConf, kubernetesConf and systemdConf. kubernetesConf Example:
#
# fluentConf : ""
# systemdConf: ""
# kubernetesConf: |-
#   <match fluent.**>
#     @type null
#   </match>
#   <source>
#     @type tail
#     @id in_tail_container_logs
#     path /var/log/containers/*.log
#     pos_file /var/log/fluentd-containers.log.pos
#     tag kubernetes.*
#     read_from_head true
#     format json
#     time_format %Y-%m-%dT%H:%M:%S.%NZ
#   </source>
#   <filter kubernetes.**>
#     @type kubernetes_metadata
#     @id filter_kube_metadata
#   </filter>

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

rbac:
  create: true
